// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VesselRegistry.Api.Data;

#nullable disable

namespace VesselRegistry.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261008172201_SeedVessels")]
    partial class SeedVessels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VesselRegistry.Api.Entities.Vessel", b =>
                {
                    b.Property<int>("VesselId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VesselId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FlagCountry")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("GrossTonnage")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("char(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VesselTypeId")
                        .HasColumnType("int");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("VesselId");

                    b.HasIndex("VesselTypeId");

                    b.HasIndex("CompanyId", "ImoNumber")
                        .IsUnique();

                    b.ToTable("Vessels");

                    b.HasData(
                        new
                        {
                            VesselId = 1,
                            CompanyId = 1,
                            VesselName = "MV Ocean Star",
                            ImoNumber = "1234567",
                            VesselTypeId = 1,
                            FlagCountry = "Sri Lanka",
                            GrossTonnage = 12500.00m,
                            YearBuilt = 2018,
                            IsActive = true,
                            CreatedBy = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            VesselId = 2,
                            CompanyId = 2,
                            VesselName = "MV Pacific Trader",
                            ImoNumber = "7654321",
                            VesselTypeId = 2,
                            FlagCountry = "Singapore",
                            GrossTonnage = 24800.00m,
                            YearBuilt = 2020,
                            IsActive = true,
                            CreatedBy = 1,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("VesselRegistry.Api.Entities.VesselType", b =>
                {
                    b.Property<int>("VesselTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VesselTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VesselTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VesselTypes");

                    b.HasData(
                        new
                        {
                            VesselTypeId = 1,
                            Name = "Bulk Carrier"
                        },
                        new
                        {
                            VesselTypeId = 2,
                            Name = "Container"
                        },
                        new
                        {
                            VesselTypeId = 3,
                            Name = "Tanker"
                        },
                        new
                        {
                            VesselTypeId = 4,
                            Name = "General Cargo"
                        },
                        new
                        {
                            VesselTypeId = 5,
                            Name = "Ro-Ro"
                        });
                });

            modelBuilder.Entity("VesselRegistry.Api.Entities.Vessel", b =>
                {
                    b.HasOne("VesselRegistry.Api.Entities.VesselType", "VesselType")
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VesselType");
                });
#pragma warning restore 612, 618
        }
    }
}
