// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VesselRegistry.Api.Data;

#nullable disable

namespace VesselRegistry.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009052441_SeedVessels")]
    partial class SeedVessels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VesselRegistry.Api.Entities.Vessel", b =>
                {
                    b.Property<int>("VesselId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VesselId"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("FlagCountry")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<decimal>("GrossTonnage")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("ImoNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("char(7)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ModifiedBy")
                        .HasColumnType("int");

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VesselTypeId")
                        .HasColumnType("int");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("VesselId");

                    b.HasIndex("VesselTypeId");

                    b.HasIndex("CompanyId", "ImoNumber")
                        .IsUnique();

                    b.ToTable("Vessels");

                    b.HasData(
                        new
                        {
                            VesselId = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Sri Lanka",
                            GrossTonnage = 12500.00m,
                            ImoNumber = "1234567",
                            IsActive = true,
                            VesselName = "MV Ocean Star",
                            VesselTypeId = 1,
                            YearBuilt = 2018
                        },
                        new
                        {
                            VesselId = 2,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Singapore",
                            GrossTonnage = 24800.00m,
                            ImoNumber = "7654321",
                            IsActive = true,
                            VesselName = "MV Pacific Trader",
                            VesselTypeId = 2,
                            YearBuilt = 2020
                        },
                        new
                        {
                            VesselId = 3,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Australia",
                            GrossTonnage = 9800.00m,
                            ImoNumber = "1000003",
                            IsActive = true,
                            VesselName = "MV Southern Cross",
                            VesselTypeId = 3,
                            YearBuilt = 2017
                        },
                        new
                        {
                            VesselId = 4,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Japan",
                            GrossTonnage = 11200.00m,
                            ImoNumber = "1000004",
                            IsActive = true,
                            VesselName = "MV Eastern Wind",
                            VesselTypeId = 4,
                            YearBuilt = 2016
                        },
                        new
                        {
                            VesselId = 5,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Malta",
                            GrossTonnage = 7600.00m,
                            ImoNumber = "1000005",
                            IsActive = true,
                            VesselName = "MV Coral Bay",
                            VesselTypeId = 5,
                            YearBuilt = 2015
                        },
                        new
                        {
                            VesselId = 6,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Greece",
                            GrossTonnage = 15300.00m,
                            ImoNumber = "1000006",
                            IsActive = true,
                            VesselName = "MV Blue Horizon",
                            VesselTypeId = 1,
                            YearBuilt = 2019
                        },
                        new
                        {
                            VesselId = 7,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Cyprus",
                            GrossTonnage = 8900.00m,
                            ImoNumber = "1000007",
                            IsActive = true,
                            VesselName = "MV Island Queen",
                            VesselTypeId = 2,
                            YearBuilt = 2014
                        },
                        new
                        {
                            VesselId = 8,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Norway",
                            GrossTonnage = 18700.00m,
                            ImoNumber = "1000008",
                            IsActive = true,
                            VesselName = "MV Golden Wave",
                            VesselTypeId = 3,
                            YearBuilt = 2018
                        },
                        new
                        {
                            VesselId = 9,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Panama",
                            GrossTonnage = 10400.00m,
                            ImoNumber = "1000009",
                            IsActive = true,
                            VesselName = "MV Silver Dawn",
                            VesselTypeId = 4,
                            YearBuilt = 2013
                        },
                        new
                        {
                            VesselId = 10,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Liberia",
                            GrossTonnage = 13200.00m,
                            ImoNumber = "1000010",
                            IsActive = true,
                            VesselName = "MV Northern Light",
                            VesselTypeId = 5,
                            YearBuilt = 2021
                        },
                        new
                        {
                            VesselId = 11,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Bahamas",
                            GrossTonnage = 14500.00m,
                            ImoNumber = "1000011",
                            IsActive = true,
                            VesselName = "MV Emerald Sea",
                            VesselTypeId = 1,
                            YearBuilt = 2012
                        },
                        new
                        {
                            VesselId = 12,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "United Kingdom",
                            GrossTonnage = 22100.00m,
                            ImoNumber = "1000012",
                            IsActive = true,
                            VesselName = "MV Atlantic Pride",
                            VesselTypeId = 2,
                            YearBuilt = 2017
                        },
                        new
                        {
                            VesselId = 13,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "India",
                            GrossTonnage = 6700.00m,
                            ImoNumber = "1000013",
                            IsActive = true,
                            VesselName = "MV Harbor Star",
                            VesselTypeId = 3,
                            YearBuilt = 2011
                        },
                        new
                        {
                            VesselId = 14,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Denmark",
                            GrossTonnage = 11900.00m,
                            ImoNumber = "1000014",
                            IsActive = true,
                            VesselName = "MV Ocean Venture",
                            VesselTypeId = 4,
                            YearBuilt = 2016
                        },
                        new
                        {
                            VesselId = 15,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Turkey",
                            GrossTonnage = 9200.00m,
                            ImoNumber = "1000015",
                            IsActive = true,
                            VesselName = "MV Sea Falcon",
                            VesselTypeId = 5,
                            YearBuilt = 2019
                        },
                        new
                        {
                            VesselId = 16,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Italy",
                            GrossTonnage = 10800.00m,
                            ImoNumber = "1000016",
                            IsActive = true,
                            VesselName = "MV Coastal Runner",
                            VesselTypeId = 1,
                            YearBuilt = 2015
                        },
                        new
                        {
                            VesselId = 17,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "United States",
                            GrossTonnage = 17600.00m,
                            ImoNumber = "1000017",
                            IsActive = true,
                            VesselName = "MV Liberty Bell",
                            VesselTypeId = 2,
                            YearBuilt = 2020
                        },
                        new
                        {
                            VesselId = 18,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 18, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Brazil",
                            GrossTonnage = 8400.00m,
                            ImoNumber = "1000018",
                            IsActive = true,
                            VesselName = "MV Rainforest",
                            VesselTypeId = 3,
                            YearBuilt = 2014
                        },
                        new
                        {
                            VesselId = 19,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 19, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Canada",
                            GrossTonnage = 12600.00m,
                            ImoNumber = "1000019",
                            IsActive = true,
                            VesselName = "MV Star Voyager",
                            VesselTypeId = 4,
                            YearBuilt = 2018
                        },
                        new
                        {
                            VesselId = 20,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "France",
                            GrossTonnage = 9900.00m,
                            ImoNumber = "1000020",
                            IsActive = true,
                            VesselName = "MV Trade Wind",
                            VesselTypeId = 5,
                            YearBuilt = 2013
                        },
                        new
                        {
                            VesselId = 21,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Portugal",
                            GrossTonnage = 7300.00m,
                            ImoNumber = "1000021",
                            IsActive = true,
                            VesselName = "MV Lighthouse",
                            VesselTypeId = 1,
                            YearBuilt = 2010
                        },
                        new
                        {
                            VesselId = 22,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Germany",
                            GrossTonnage = 16400.00m,
                            ImoNumber = "1000022",
                            IsActive = true,
                            VesselName = "MV Sea Explorer",
                            VesselTypeId = 2,
                            YearBuilt = 2021
                        },
                        new
                        {
                            VesselId = 23,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "Indonesia",
                            GrossTonnage = 13800.00m,
                            ImoNumber = "1000023",
                            IsActive = true,
                            VesselName = "MV Royal Palm",
                            VesselTypeId = 3,
                            YearBuilt = 2016
                        },
                        new
                        {
                            VesselId = 24,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "South Korea",
                            GrossTonnage = 20100.00m,
                            ImoNumber = "1000024",
                            IsActive = true,
                            VesselName = "MV Cargo Master",
                            VesselTypeId = 4,
                            YearBuilt = 2019
                        },
                        new
                        {
                            VesselId = 25,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2026, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = 1,
                            FlagCountry = "New Zealand",
                            GrossTonnage = 8100.00m,
                            ImoNumber = "1000025",
                            IsActive = true,
                            VesselName = "MV Ocean Pearl",
                            VesselTypeId = 5,
                            YearBuilt = 2012
                        });
                });

            modelBuilder.Entity("VesselRegistry.Api.Entities.VesselType", b =>
                {
                    b.Property<int>("VesselTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VesselTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VesselTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VesselTypes");

                    b.HasData(
                        new
                        {
                            VesselTypeId = 1,
                            Name = "Bulk Carrier"
                        },
                        new
                        {
                            VesselTypeId = 2,
                            Name = "Container"
                        },
                        new
                        {
                            VesselTypeId = 3,
                            Name = "Tanker"
                        },
                        new
                        {
                            VesselTypeId = 4,
                            Name = "General Cargo"
                        },
                        new
                        {
                            VesselTypeId = 5,
                            Name = "Ro-Ro"
                        });
                });

            modelBuilder.Entity("VesselRegistry.Api.Entities.Vessel", b =>
                {
                    b.HasOne("VesselRegistry.Api.Entities.VesselType", "VesselType")
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VesselType");
                });
#pragma warning restore 612, 618
        }
    }
}
